# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secureauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthactivity',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0411\u0440\u0430\u0443\u0437\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='userauthactivity',
            name='confirm_method',
            field=models.CharField(blank=True, choices=[(b'', b'---'), (b'code', '\u043f\u043e \u043a\u043e\u0434\u0443'), (b'token', '\u0441 \u043f\u043e\u043c\u043e\u0449\u044c\u044e \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f'), (b'phone', '\u043f\u043e \u0441\u043c\u0441'), (b'question', '\u043f\u043e \u0432\u043e\u043f\u0440\u043e\u0441\u0443')], max_length=10, null=True, verbose_name='\u041c\u0435\u0442\u043e\u0434 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='userauthactivity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='userauthactivity',
            name='geo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0413\u0415\u041e \u0434\u0430\u043d\u043d\u044b\u0435'),
        ),
        migrations.AlterField(
            model_name='userauthactivity',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='last_verified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthip',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthip',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthiprange',
            name='ip_data',
            field=models.CharField(help_text=b'xxx.xxx.xxx.xxx or xxx.xxx.xxx.xxx/24', max_length=18, verbose_name='IP/\u041f\u043e\u0434\u0441\u0435\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthiprange',
            name='is_ip',
            field=models.BooleanField(default=False, verbose_name='\u042d\u0442\u043e IP \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='userauthlogging',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthlogging',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthnotification',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthnotification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='last_verified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthphone',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='last_verified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='question',
            field=models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthquestion',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='last_verified',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
